# Generated by Django 5.2.8 on 2025-11-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
