# Generated by Django 5.2.8 on 2026-02-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_file_expiry_date_remove_file_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileshare",
            name="granted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_file_shares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foldershare",
            name="granted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_folder_shares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
