# Generated by Django 5.2.8 on 2026-02-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_fileshare_granted_by_foldershare_granted_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="folder",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DELETED", "Deleted"),
                    ("ARCHIVED", "Archived"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
