# Generated by Django 5.2.8 on 2026-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_folder_is_deleted_folder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileshare",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="foldershare",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
