# Generated by Django 5.2.8 on 2026-02-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_file_locked_at_file_locked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("GRANT", "Access Granted"),
                    ("REVOKE", "Access Revoked"),
                    ("EXPIRY", "Access Expired"),
                    ("TRANSFER", "Ownership Transferred"),
                    ("RENAME", "File Renamed"),
                    ("DELETE", "File Deleted"),
                    ("EDIT", "File Content Modified"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="file",
            name="type",
            field=models.CharField(max_length=255),
        ),
    ]
