# Generated by Django 5.2.8 on 2026-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_auditlog_action_alter_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ocr_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ocr_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
