# Generated by Django 6.0.2 on 2026-03-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_file_ocr_extracted_at_file_ocr_status_file_ocr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('EXPIRY', 'Expiry Reminder'), ('SHARE', 'Document Shared'), ('SYSTEM', 'System Alert'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('INFO', 'Information')], default='SYSTEM', max_length=20),
        ),
    ]
