# Generated by Django 5.2.8 on 2026-03-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_file_ocr_extracted_at_file_ocr_status_file_ocr_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="translated_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="translation_language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="translation_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("EXPIRY", "Expiry Reminder"),
                    ("SHARE", "Document Shared"),
                    ("SYSTEM", "System Alert"),
                    ("SUCCESS", "Success"),
                    ("ERROR", "Error"),
                    ("INFO", "Information"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
    ]
