# Generated by Django 5.2.8 on 2026-03-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_notification_type"),
        ("api", "0014_file_translated_text_file_translation_language_and_more"),
    ]

    operations = []
