# Generated by Django 5.2.8 on 2025-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_folder_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
