# Generated by Django 5.2.8 on 2026-02-14 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_file_updated_at_folder_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="file",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="file",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DELETED", "Deleted"),
                    ("ARCHIVED", "Archived"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GRANT", "Access Granted"),
                            ("REVOKE", "Access Revoked"),
                            ("EXPIRY", "Access Expired"),
                            ("TRANSFER", "Ownership Transferred"),
                            ("RENAME", "File Renamed"),
                            ("DELETE", "File Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.file",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
