# Generated by Django 5.2.8 on 2026-02-14 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_fileshare_message_foldershare_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
